version: '3.8'
services:
  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.local
    depends_on:
      - python-backend

  python-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env.local 